api = "0.7"

[buildpack]
  homepage = "https://github.com/paketo-buildpacks/nodejs"
  id = "paketo-buildpacks/nodejs"
  name = "Paketo Buildpack for Node.js"

  [[buildpack.licenses]]
    type = "Apache-2.0"
    uri = "https://github.com/paketo-buildpacks/nodejs/blob/main/LICENSE"

[metadata]
  include-files = ["buildpack.toml"]

[[order]]

  [[order.group]]
    # renovate: depName=paketo-buildpacks/ca-certificates
    id = "paketo-buildpacks/ca-certificates"
    optional = true
    version = "3.10.1"

  [[order.group]]
    # renovate: depName=paketo-buildpacks/watchexec
    id = "paketo-buildpacks/watchexec"
    optional = true
    version = "3.5.0"

  [[order.group]]
    # renovate: depName=paketo-buildpacks/node-engine
    id = "paketo-buildpacks/node-engine"
    version = "5.4.1"

  [[order.group]]
    # renovate: depName=paketo-buildpacks/yarn
    id = "paketo-buildpacks/yarn"
    version = "1.3.36"

  [[order.group]]
    # renovate: depName=paketo-buildpacks/yarn-install
    id = "paketo-buildpacks/yarn-install"
    version = "2.1.18"

  [[order.group]]
    # renovate: depName=paketo-buildpacks/node-run-script
    id = "paketo-buildpacks/node-run-script"
    optional = true
    version = "2.0.12"

  [[order.group]]
    # renovate: depName=paketo-buildpacks/node-start
    id = "paketo-buildpacks/node-start"
    optional = true
    version = "2.1.24"

  [[order.group]]
    # renovate: depName=paketo-buildpacks/yarn-start
    id = "paketo-buildpacks/yarn-start"
    optional = true
    version = "2.0.35"

  [[order.group]]
    # renovate: depName=paketo-buildpacks/procfile
    id = "paketo-buildpacks/procfile"
    optional = true
    version = "5.11.0"

  [[order.group]]
    # renovate: depName=paketo-buildpacks/environment-variables
    id = "paketo-buildpacks/environment-variables"
    optional = true
    version = "4.9.0"

  [[order.group]]
    # renovate: depName=paketo-buildpacks/image-labels
    id = "paketo-buildpacks/image-labels"
    optional = true
    version = "4.9.0"

[[order]]

  [[order.group]]
    # renovate: depName=paketo-buildpacks/ca-certificates
    id = "paketo-buildpacks/ca-certificates"
    optional = true
    version = "3.10.1"

  [[order.group]]
    # renovate: depName=paketo-buildpacks/watchexec
    id = "paketo-buildpacks/watchexec"
    optional = true
    version = "3.5.0"

  [[order.group]]
    # renovate: depName=paketo-buildpacks/node-engine
    id = "paketo-buildpacks/node-engine"
    version = "5.4.1"

  [[order.group]]
    # renovate: depName=paketo-buildpacks/npm-install
    id = "paketo-buildpacks/npm-install"
    version = "1.9.4"

  [[order.group]]
    # renovate: depName=paketo-buildpacks/node-run-script
    id = "paketo-buildpacks/node-run-script"
    optional = true
    version = "2.0.12"

  [[order.group]]
    # renovate: depName=paketo-buildpacks/node-start
    id = "paketo-buildpacks/node-start"
    optional = true
    version = "2.1.24"

  [[order.group]]
    # renovate: depName=paketo-buildpacks/npm-start
    id = "paketo-buildpacks/npm-start"
    optional = true
    version = "2.1.12"

  [[order.group]]
    # renovate: depName=paketo-buildpacks/procfile
    id = "paketo-buildpacks/procfile"
    optional = true
    version = "5.11.0"

  [[order.group]]
    # renovate: depName=paketo-buildpacks/environment-variables
    id = "paketo-buildpacks/environment-variables"
    optional = true
    version = "4.9.0"

  [[order.group]]
    # renovate: depName=paketo-buildpacks/image-labels
    id = "paketo-buildpacks/image-labels"
    optional = true
    version = "4.9.0"

[[order]]

  [[order.group]]
    # renovate: depName=paketo-buildpacks/ca-certificates
    id = "paketo-buildpacks/ca-certificates"
    optional = true
    version = "3.10.1"

  [[order.group]]
    # renovate: depName=paketo-buildpacks/watchexec
    id = "paketo-buildpacks/watchexec"
    optional = true
    version = "3.5.0"

  [[order.group]]
    # renovate: depName=paketo-buildpacks/node-engine
    id = "paketo-buildpacks/node-engine"
    version = "5.4.1"

  [[order.group]]
    # renovate: depName=paketo-buildpacks/node-start
    id = "paketo-buildpacks/node-start"
    version = "2.1.24"

  [[order.group]]
    # renovate: depName=paketo-buildpacks/procfile
    id = "paketo-buildpacks/procfile"
    optional = true
    version = "5.11.0"

  [[order.group]]
    # renovate: depName=paketo-buildpacks/environment-variables
    id = "paketo-buildpacks/environment-variables"
    optional = true
    version = "4.9.0"

  [[order.group]]
    # renovate: depName=paketo-buildpacks/image-labels
    id = "paketo-buildpacks/image-labels"
    optional = true
    version = "4.9.0"
